// <auto-generated />
using System;
using BlogBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlogBackend.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20260402044722_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlogBackend.Models.BlogPost", b =>
                {
                    b.Property<int>("MaBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBaiViet"));

                    b.Property<string>("HinhAnhBia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaBaiViet");

                    b.ToTable("BlogPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
