// <auto-generated />
using System;
using BlogBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlogBackend.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20260903083617_AddDirectChatSessions")]
    partial class AddDirectChatSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlogBackend.Models.BlogPost", b =>
                {
                    b.Property<int>("MaBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBaiViet"));

                    b.Property<string>("HinhAnhBia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LuotTim")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaBaiViet");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("BlogBackend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("MaBaiViet")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayBinhLuan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaBaiViet", "NgayBinhLuan");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BlogBackend.Models.DirectChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsFromAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReadByAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReadByUser")
                        .HasColumnType("boolean");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("DirectChatMessages");
                });

            modelBuilder.Entity("BlogBackend.Models.DirectChatSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VisitorEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VisitorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("WantsEmailNotification")
                        .HasColumnType("boolean");

                    b.HasKey("SessionId");

                    b.ToTable("DirectChatSessions");
                });

            modelBuilder.Entity("BlogBackend.Models.PortfolioConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PortfolioConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JsonData = "{}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
